# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install GNU core utilities (those that come with OS X are outdated)
install coreutils
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`:
# $PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH"

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
install findutils

# Install Bash 4
install bash
install bash-completion

# Install other useful binaries
install git
# This installs `npm` too using the recommended installation method
install node
install wget
install ack
install imagemagick --with-webp
install lynx
install p7zip
install tree
install webkit2png
install graphicsmagick
install ffmpeg

# Remove outdated versions from the cellar
cleanup
