add_newline = true
command_timeout = 200
format = "$hostname[$directory$git_branch$git_status]($style)$nodejs$rust$python$character"

[hostname]
ssh_only = true
format = '[\($hostname\)]($style) '
style = "cyan"

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = "! "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = "≡ "
staged     = ""
renamed    = ""
deleted    = ""

[nodejs]
format = "[$symbol:$version]($style) "
version_format = "${raw}"
symbol = "N"
style = "cyan"

[rust]
format = "[$symbol:$version]($style) "
version_format = "${raw}"
symbol = "R"
style = "cyan"

[python]
format = "[$symbol:$version]($style) "
version_format = "${raw}"
symbol = "P"
style = "cyan"
