# Options
set -sg terminal-overrides ",*:RGB"  # true color support
set -g escape-time 0  # disable delays on escape sequences
set -g mouse on
set -g renumber-windows on  # keep numbering sequential
set -g repeat-time 1000  # increase "prefix-free" window
set -g set-titles on
set -g focus-events on
set -g status-position bottom
set -w -g wrap-search off
set -g set-clipboard on
set -w -g automatic-rename off

# Options: start indexes from 1
set -g base-index 1
set -g pane-base-index 1

# Change prefix
unbind C-b
set -g prefix `
bind ` send-prefix

# Theme: borders
set -g pane-border-lines single
set -g pane-border-status top
# set -g pane-border-format '#[bold] #{pane_index} #[default]'
set -g pane-border-format '#[bold] #{pane_index} / #(sleep 1; ps -t #{pane_tty} -o args= | head -n 2) #[default]'
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=magenta

# Theme: status
set -g status-style bg=default,fg=black,bright
set -g status-left ""
set -g status-right "#[fg=magenta,bright]#S"

# Theme: status (windows)
set -g window-status-format " ● #{window_index}/ #{window_name} "
set -g window-status-current-format " ● #{window_name} "
set -g window-status-current-style "#{?window_zoomed_flag,fg=yellow,fg=magenta#,nobold}"
set -g window-status-bell-style "fg=red,nobold"

# Keybindings: select session ordering
bind s choose-tree -sZ -O time

# Keybindings: disable repeat for arrows
bind Up select-pane -U
bind Left select-pane -L
bind Down select-pane -D
bind Right select-pane -R

# Keybindings: split
unbind %
bind | split-window -h -c '#{pane_current_path}' # normally prefix-%
unbind '"'
bind '\' split-window -v -c '#{pane_current_path}' # normally prefix-""

bind c new-window -c "#{pane_current_path}"

bind PgUp next-window
bind PgDn  previous-window

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# Shell
set -g default-shell /usr/bin/fish
set -s default-terminal 'tmux-256color'

run '~/.tmux/plugins/tpm/tpm'
